name: Check (nix)
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
jobs:
  checks:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v35
      - name: Run Checks
        id: run_checks
        run: |
          set -o pipefail
          ERROR=$(nix flake check . 2>&1)
          { echo "errormsg<<EOF"; echo "$ERROR"; echo "EOF"; } >> "$GITHUB_OUTPUT"
      - name: Print full failure logs
        if: ${{ failure() && steps.run_checks.conclusion == 'failure' }}
        run: nix log "$(grep "For full logs, run" <<< "${{ steps.run_checks.outputs.errormsg }}" | grep -oE "/nix/store/.*.drv")"
