# This is for checking this repo, and is not designed to be re-used.
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  check_repo:
    uses: rbpatt2019/shared-workflows/.github/workflows/reusable/check_nix.yaml@main
    with:
      os: ubuntu-latest
